name: Publish
on: [pull_request]
jobs:
  generate-link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ‘€
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      
      - name: Build ðŸ› 
        run: npm i
        run: npm run build

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: staging # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
